# Autocomplete
"$schema" = 'https://starship.rs/config-schema.json'

# Config
add_newline = true

[aws]
disabled = true

[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

[gcloud]
disabled = true

[git_branch]
symbol = 'î‚  '
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_status]
ahead = 'â¡ï¸${count}'
diverged = 'â¡ï¸${ahead_count}â¬…ï¸${behind_count}'
behind = 'â¬…ï¸${count}'
staged = 'ğŸŸ¢+$count'

[golang]
format = 'via [$version($mod_version)]($style)'

[nodejs]
format = 'via [$symbol$version](bold green) '